# language: es

            Característica: designar una persona a un cargo docente
            actividad central de información de la escuela secundaria

            Esquema del escenario: Designación de persona en cargos NO cubiertos aún en el perído indicado de forma existosa
            Dada la persona con <DNI> "<nombre>" y "<apellido>"
            Y que se asigna al cargo con tipo de designación "<tipo>" y "<nombreDesignación>" en la división "<año>" "<número>" "<turno>"
            Y se designa por el período "<fechaDesde>" "<fechaHasta>"
            Cuando se presiona el botón guardar
            Entonces se espera el siguiente <status> y "<respuesta>"

            Ejemplos:
            | DNI      | nombre      | apellido     | tipo               | nombreDesignación    | año | número | turno  | fechaDesde | fechaHasta | status | respuesta                                                                                                      |
            | 10100100 | Alberto     | Lopez        | CARGO              | Vicedirector/a       |     |        |        | 2023-03-01 |            | 200    | Alberto Lopez ha sido designado/a como Vicedirector/a exitosamente                                             |
            | 20200200 | Susana      | Álvarez      | CARGO              | Preceptor/a          |     |        |        | 2023-03-01 | 2023-12-31 | 200    | Susana Álvarez ha sido designado/a como Preceptor/a exitosamente                                               |
            | 40400400 | Marísa      | Amuchástegui | ESPACIO_CURRICULAR | Historia             | 5   | 2      | Mañana | 2023-03-01 |            | 200    | Marísa Amuchástegui ha sido designado/a a la asignatura Historia a la división 5º 2º turno Mañana exitosamente |
            | 50500500 | Raúl        | Gómez        | ESPACIO_CURRICULAR | Geografía            | 3   | 1      | Tarde  | 2023-03-01 | 2025-12-31 | 200    | Raúl Gómez ha sido designado/a a la asignatura Geografía a la división 3º 1º turno Tarde exitosamente          |
            | 20000000 | Rosalía     | Fernandez    | CARGO              | Auxiliar ADM         |     |        |        | 2023-01-01 | 2023-12-31 | 200    | Rosalía Fernandez ha sido designado/a como Auxiliar ADM exitosamente                                           |
            | 90900900 | Ermenegildo | Sábat        | ESPACIO_CURRICULAR | Física               | 2   | 3      | Mañana | 2023-03-01 |            | 200    | Ermenegildo Sábat ha sido designado/a a la asignatura Física a la división 2º 3º turno Mañana exitosamente     |
            | 11110110 | María Rosa  | Gallo        | ESPACIO_CURRICULAR | Matemáticas          | 1   | 1      | Tarde  | 2023-03-01 |            | 200    | María Rosa Gallo ha sido designado/a a la asignatura Matemáticas a la división 1º 1º turno Tarde exitosamente  |
            | 12120120 | Homero      | Manzi        | ESPACIO_CURRICULAR | Tecnología           | 4   | 3      | Mañana | 2023-03-01 |            | 200    | Homero Manzi ha sido designado/a a la asignatura Tecnología a la división 4º 3º turno Mañana exitosamente      |
            | 88888888 | Marisa      | Balaguer     | ESPACIO_CURRICULAR | Física               | 2   | 3      | Mañana | 2022-03-01 | 2022-12-01 | 200    | Marisa Balaguer ha sido designado/a a la asignatura Física a la división 2º 3º turno Mañana exitosamente       |
            | 88600000 | Marta       | Ríos         | CARGO              | Coordinador TIC      |     |        |        | 2024-03-01 |            | 200    | Marta Ríos ha sido designado/a como Coordinador TIC exitosamente                                               |
            | 88700000 | Rosalía     | Ramón        | CARGO              | Portero/a            |     |        |        | 2024-03-01 |            | 200    | Rosalía Ramón ha sido designado/a como Portero/a exitosamente                                                  |
            | 88800000 | José        | Pérez        | CARGO              | Jefe de Departamento |     |        |        | 2024-03-01 |            | 200    | José Pérez ha sido designado/a como Jefe de Departamento exitosamente                                          |
            | 88100000 | Raúl        | Orellanos    | ESPACIO_CURRICULAR | Lengua               | 1   | 2      | Tarde  | 2024-03-01 |            | 200    | Raúl Orellanos ha sido designado/a a la asignatura Lengua a la división 1º 2º turno Tarde exitosamente         |
            | 88200000 | Matías      | Barto        | ESPACIO_CURRICULAR | Inglés               | 3   | 2      | Mañana | 2024-03-01 |            | 200    | Matías Barto ha sido designado/a a la asignatura Inglés a la división 3º 2º turno Mañana exitosamente          |
            | 88300000 | Andrea      | Sosa         | ESPACIO_CURRICULAR | Química              | 6   | 1      | Noche  | 2024-03-01 |            | 200    | Andrea Sosa ha sido designado/a a la asignatura Química a la división 6º 1º turno Noche exitosamente           |
            | 88400000 | Laura       | Barrientos   | ESPACIO_CURRICULAR | Biología             | 2   | 2      | Mañana | 2024-03-01 |            | 200    | Laura Barrientos ha sido designado/a a la asignatura Biología a la división 2º 2º turno Mañana exitosamente    |
            | 88500000 | Natalia     | Zabala       | ESPACIO_CURRICULAR | Historia             | 5   | 1      | Tarde  | 2024-03-01 |            | 200    | Natalia Zabala ha sido designado/a a la asignatura Historia a la división 5º 1º turno Tarde exitosamente       |
            | 10101010 | Frank       | Sinatra      | CARGO              | Secretario/a               |     |        |        | 2024-03-01 |            | 200    | Frank Sinatra ha sido designado/a como Secretario/a exitosamente               |
            | 20202020 | Pity        | Alvarez      | CARGO              | Bibliotecario/a            |     |        |        | 2024-03-01 |            | 200    | Pity Alvarez ha sido designado/a como Bibliotecario/a exitosamente             |
            | 30303030 | Elvis       | Presley      | CARGO              | Regente                    |     |        |        | 2024-03-01 |            | 200    | Elvis Presley ha sido designado/a como Regente exitosamente                    |
            | 40404040 | Julian      | Alvarez      | CARGO              | Jefe de Taller             |     |        |        | 2024-03-01 |            | 200    | Julian Alvarez ha sido designado/a como Jefe de Taller exitosamente            |
            | 50505050 | Paul        | Pogba        | CARGO              | Encargado de Medios        |     |        |        | 2024-03-01 |            | 200    | Paul Pogba ha sido designado/a como Encargado de Medios exitosamente           |
            | 60606060 | Kilian      | Mbappe       | CARGO              | Coordinador de Turno       |     |        |        | 2024-03-01 |            | 200    | Kilian Mbappe ha sido designado/a como Coordinador de Turno exitosamente       |
            | 70707070 | Lionel      | Messi        | CARGO              | Prosecretario/a            |     |        |        | 2024-03-01 |            | 200    | Lionel Messi ha sido designado/a como Prosecretario/a exitosamente             |
            | 80808080 | Cristiano   | Ronaldo      | CARGO              | Referente ESI              |     |        |        | 2024-03-01 |            | 200    | Cristiano Ronaldo ha sido designado/a como Referente ESI exitosamente          |
            | 90909090 | Ariel       | Ortega       | CARGO              | Coordinador de Biblioteca  |     |        |        | 2024-03-01 |            | 200    | Ariel Ortega ha sido designado/a como Coordinador de Biblioteca exitosamente   |
            | 11111111 | Franco      | Mastantuono  | CARGO              | Jefe de Laboratorio        |     |        |        | 2024-03-01 |            | 200    | Franco Mastantuono ha sido designado/a como Jefe de Laboratorio exitosamente   |
            | 12121212 | Ricardo     | Darin        | CARGO              | Psicopedagogo/a            |     |        |        | 2024-03-01 |            | 200    | Ricardo Darin ha sido designado/a como Psicopedagogo/a exitosamente            |
            | 13131313 | Guillermo   | Francella    | CARGO              | Jefe de Preceptores        |     |        |        | 2024-03-01 |            | 200    | Guillermo Francella ha sido designado/a como Jefe de Preceptores exitosamente  |
            | 14141414 | Martin      | Palermo      | CARGO              | Coordinador de Área        |     |        |        | 2024-03-01 |            | 200    | Martin Palermo ha sido designado/a como Coordinador de Área exitosamente       |
            | 15151515 | Enzo        | Perez        | CARGO              | Asesor Pedagógico          |     |        |        | 2024-03-01 |            | 200    | Enzo Perez ha sido designado/a como Asesor Pedagógico exitosamente             |
            | 16161616 | Gianluigi   | Donnaruma    | CARGO              | Coordinador de Convivencia |     |        |        | 2024-03-01 |            | 200    | Gianluigi Donnaruma ha sido designado/a como Coordinador de Convivencia exitosamente |
            | 17171717 | Gianluigi   | Buffon       | ESPACIO_CURRICULAR | Computación                | 3   | 2      | Mañana | 2024-03-01 |            | 200    | Gianluigi Buffon ha sido designado/a a la asignatura Computación a la división 3º 2º turno Mañana exitosamente          |
            | 18181818 | Mario       | Kempes       | ESPACIO_CURRICULAR | Educación Plástica         | 1   | 1      | Tarde  | 2024-03-01 |            | 200    | Mario Kempes ha sido designado/a a la asignatura Educación Plástica a la división 1º 1º turno Tarde exitosamente        |
            | 19191919 | Diego       | Maradona     | ESPACIO_CURRICULAR | Música                     | 2   | 2      | Mañana | 2024-03-01 |            | 200    | Diego Maradona ha sido designado/a a la asignatura Música a la división 2º 2º turno Mañana exitosamente                 |

